# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'
      - run: yarn
      - run: yarn run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            docs
            package.json
          retention-days: 1

  test:
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - uses: actions/download-artifact@v5
        with:
          name: build

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: coverage
          path: |
            coverage
            package.json
          retention-days: 1

  test_pr:
    needs: build
    if: ${{ github.event_name == 'pull_request' }}
    name: Test PR (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        node-version: [ 24 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - uses: actions/download-artifact@v5
        with:
          name: build

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: yarn test
        timeout-minutes: 1

  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - uses: actions/download-artifact@v5
        with:
          merge-multiple: true

      - name: Check artifacts
        run: |
          ls -l
          cd coverage && ls -l

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_USER: 'x-access-token'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_EMAIL: 'antongolub@antongolub.com'
          GIT_COMMITTER_NAME: 'Anton Golub'
        run: npx zx-semrel

      - name: Push coverage
        run: |
          [ -e ${{ github.workspace }}/coverage/lcov.info ] && echo "exists" || echo "missing"
          yarn install --prod
          node ./src/main/js/cli.js ${{ github.workspace }}/coverage/lcov.info https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git/coverage/${{ github.event.repository.updated_at }}-${{ github.sha }} --message='chore: push coverage for ${{ github.sha }}'
